FROM node:20-alpine3.17 as build-stage

WORKDIR /app

COPY frontend /app

RUN npm install

RUN npm run build

FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html

COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 443
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]