services:
  web:
    build: "."
    ports:
      - "9871:9871"
    env_file: .env
    environment:
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      LOG_DIR: ${LOG_DIR}
      LOG_LEVEL: ${LOG_LEVEL}
    stop_signal: SIGINT
    restart: always
    volumes:
      - ./log:/var/log/dormhub
  db:
    image: mariadb:latest
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
  ftp:
    image: delfer/alpine-ftp-server
    env_file: .env
    environment:
      USERS: ${FTP_FULLLOGIN}
    stop_signal: SIGINT
    restart: always
    volumes:
      - ./public_html:/ftp/${FTP_USER}/images
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./public_html:/usr/share/nginx/html
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - /home/gh-action/web/certs:/etc/ssl
    depends_on:
      - ftp

#  qr_generator:
#    build: "./qr_generator"
#    stop_signal: SIGINT
#    restart: always
#  maintenance:
#    build: "./misc"
#    env_file: .env
#    restart: on-failure
#    stop_signal: SIGKILL
volumes:
  mysql_data:
